---
title: Bradley Wright
baseURL: "/"
params:
  palette: green
  header:
    title: Bradley Wright
    tagline: My thoughts and opinions on life.
    logo_img: images/logo.png
    bg_img: images/header-bg.jpg
    has_nav: true
    has_social: true
  footer:
    content: "&copy; BradleyWright All rights reserved."
    links:
    - text: Made with Stackbit
      url: https://www.stackbit.com
      new_window: true
disableKinds:
- RSS
